version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SKIP_MONGODB=true
      - STACK_RPC_URL=https://rpc.blaze.soniclabs.com
      - STACK_TESTNET_RPC_URL=https://rpc.blaze.soniclabs.com
      - NETWORK_CHAIN_ID=57054
      - WEB3_PROVIDER_URL=https://rpc.blaze.soniclabs.com
    volumes:
      - ./:/app
      - /app/node_modules 